name: CI

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
      paths:
        - '.github/**'
  workflow_dispatch:

jobs:
  get-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Get assets
        run: |
          bash ${{ github.workspace }}/.github/get_themes.sh

      - name: Continuous Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Themes and Icons"
          tag_name: "Continuous"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: assets/*
        continue-on-error: false

